In [1]:
from pathlib import Path
import pandas as pd
import json
import mavehgvs
dataset_path = Path("/data/dzeiberg/mave_calibration/data/Giacomelli_p53_wtNutlin3/")
assert dataset_path.exists()

In [2]:
data = pd.read_csv(dataset_path / "raw" / "urn_mavedb_00000068-a-1_scores.csv")

In [3]:
data = data.dropna(subset=["hgvs_pro",'score'])

In [4]:
data

,accession,hgvs_nt,hgvs_splice,hgvs_pro,score
16,urn:mavedb:00000068-a-1#17,NaN,NaN,p.Ter394Tyr,0.029980
17,urn:mavedb:00000068-a-1#18,NaN,NaN,p.Ter394Trp,0.062089
18,urn:mavedb:00000068-a-1#19,NaN,NaN,p.Ter394Val,-0.520054
19,urn:mavedb:00000068-a-1#20,NaN,NaN,p.Ter394Thr,-0.398481
20,urn:mavedb:00000068-a-1#21,NaN,NaN,p.Ter394Ser,-0.317579
...,...,...,...,...,...
8269,urn:mavedb:00000068-a-1#8270,NaN,NaN,p.Met1Phe,0.151947
8270,urn:mavedb:00000068-a-1#8271,NaN,NaN,p.Met1Glu,-0.604673
8271,urn:mavedb:00000068-a-1#8272,NaN,NaN,p.Met1Asp,0.151947
8272,urn:mavedb:00000068-a-1#8273,NaN,NaN,p.Met1Cys,-0.874059
8273,urn:mavedb:00000068-a-1#8274,NaN,NaN,p.Met1Ala,-0.608318

In [5]:
data.to_csv(dataset_path / 'scoreset.csv', index=False)