In [1]:
import pandas as pd
from pathlib import Path
from mavehgvs import Variant
dataset_path = Path("/mnt/i/bio/mave_curation/Kotler_TP53_inVivoEnrichment/")

In [2]:
data = pd.read_excel(dataset_path / "raw" / 'mmc6.xlsx')

In [3]:
data

,Identifier,Var_seq,Identifier.1,SubLib,Backbone,Mut_type,Position,Seq_change,Codon_num,AA_change,Silent,Enrichment_invivo
0,400063,AATAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,400063,DBDD,wt,AASub,736,ATG>AAT,246,M>N,False,-0.268687
1,400064,AGTAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,400064,DBDD,wt,AASub,736,ATG>AGT,246,M>S,False,-0.170385
2,400065,CAGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,400065,DBDD,wt,AASub,736,ATG>CAG,246,M>Q,False,-3.056508
3,400066,CCGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,400066,DBDD,wt,AASub,736,ATG>CCG,246,M>P,False,-2.620823
4,400067,GAGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,400067,DBDD,wt,AASub,736,ATG>GAG,246,M>E,False,-2.243882
...,...,...,...,...,...,...,...,...,...,...,...,...
965,403428,ATGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,403428,DBDD,wt,Del,874,A>0,292,K>F.S,False,-0.584308
966,403430,ATGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,403430,DBDD,wt,Ins,874,A,292,K>F.S,False,-0.951854
967,403438,ATGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,403438,DBDD,wt,Ins,875,T,292,K>F.S,False,-0.854025
968,403442,ATGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,403442,DBDD,wt,Ins,876,C,292,K>F.S,False,-4.042455
969,403451,ATGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,403451,DBDD,wt,Ins,877,T,293,G>F.S,False,-3.440203

In [4]:
data.Mut_type.unique()

array(['AASub', 'Del', 'Del2AA', 'DelAA', 'Sub', 'Ins', 'Sub2bp',
       'IARC.InDel.GeneVars', 'STOP', 'IARC.InDel.SomatMuts'],
      dtype=object)

In [5]:
subset = data[(~data.AA_change.isna()) & (data.AA_change.str.len() == 3) & (data.Mut_type != "DelAA")]

In [6]:
subset

,Identifier,Var_seq,Identifier.1,SubLib,Backbone,Mut_type,Position,Seq_change,Codon_num,AA_change,Silent,Enrichment_invivo
0,400063,AATAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,400063,DBDD,wt,AASub,736,ATG>AAT,246,M>N,False,-0.268687
1,400064,AGTAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,400064,DBDD,wt,AASub,736,ATG>AGT,246,M>S,False,-0.170385
2,400065,CAGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,400065,DBDD,wt,AASub,736,ATG>CAG,246,M>Q,False,-3.056508
3,400066,CCGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,400066,DBDD,wt,AASub,736,ATG>CCG,246,M>P,False,-2.620823
4,400067,GAGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,400067,DBDD,wt,AASub,736,ATG>GAG,246,M>E,False,-2.243882
...,...,...,...,...,...,...,...,...,...,...,...,...
932,403245,ATGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,403245,DBDD,wt,AASub,859,GAG>CCG,287,E>P,False,-4.052793
935,403255,ATGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,403255,DBDD,wt,STOP,859,GAG>TAA,287,E>*,False,-1.257742
936,403258,ATGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,403258,DBDD,wt,Sub,859,G>T,287,E>*,False,-1.776986
946,403284,ATGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,403284,DBDD,wt,AASub,862,AAT>TAA,288,N>*,False,-1.584004
959,403400,ATGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,403400,DBDD,wt,STOP,871,AAG>TAA,291,K>*,False,-1.846113

In [7]:
from Bio.PDB.Polypeptide import protein_letters_3to1
protein_letters_1to3 = {v: k.title() for k, v in protein_letters_3to1.items()}
protein_letters_1to3["*"] = "Ter"
def make_hgvs_pro(r):
    return f"p.{protein_letters_1to3[r.AA_change[0]]}{r.Codon_num}{protein_letters_1to3[r.AA_change[-1]]}"

In [8]:
subset = subset.assign(hgvs_pro=subset.apply(make_hgvs_pro, axis=1))
subset = subset.rename(columns={'Enrichment_invivo':'score'})

In [9]:
subset[subset.hgvs_pro.duplicated(keep=False)]

,Identifier,Var_seq,Identifier.1,SubLib,Backbone,Mut_type,Position,Seq_change,Codon_num,AA_change,Silent,score,hgvs_pro
37,400131,ATGAATTGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,400131,DBDD,wt,Sub2bp,741,CC>TT,248,R>W,False,-3.803088,p.Arg248Trp
42,400140,ATGAACACCAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,400140,DBDD,wt,AASub,742,CGG>ACC,248,R>T,False,-0.112723,p.Arg248Thr
43,400141,ATGAACACGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,400141,DBDD,wt,AASub,742,CGG>ACG,248,R>T,False,-3.158992,p.Arg248Thr
44,400142,ATGAACACTAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,400142,DBDD,wt,AASub,742,CGG>ACT,248,R>T,False,-2.521489,p.Arg248Thr
45,400145,ATGAACAGTAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,400145,DBDD,wt,AASub,742,CGG>AGT,248,R>S,False,-1.156657,p.Arg248Ser
...,...,...,...,...,...,...,...,...,...,...,...,...,...
918,403223,ATGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,403223,DBDD,wt,Sub,856,G>A,286,E>K,False,-1.082056,p.Glu286Lys
929,403236,ATGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,403236,DBDD,wt,Sub,858,A>C,286,E>D,False,-2.355171,p.Glu286Asp
930,403238,ATGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,403238,DBDD,wt,Sub,858,A>T,286,E>D,False,-1.024162,p.Glu286Asp
935,403255,ATGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,403255,DBDD,wt,STOP,859,GAG>TAA,287,E>*,False,-1.257742,p.Glu287Ter
936,403258,ATGAACCGGAGGCCCATCCTCACCATCATCACACTGGAAGACTCCA...,403258,DBDD,wt,Sub,859,G>T,287,E>*,False,-1.776986,p.Glu287Ter

In [10]:
aggregated = subset.groupby("hgvs_pro").agg({"score": "mean"}).reset_index()

In [11]:
aggregated

        hgvs_pro     score
0    p.Ala276Arg -3.189259
1    p.Ala276Asn -4.895933
2    p.Ala276Gly -1.904301
3    p.Ala276Ile -3.577072
4    p.Ala276Phe  1.458132
..           ...       ...
382  p.Val274Pro -1.263990
383  p.Val274Ser -0.929079
384  p.Val274Ter -2.384789
385  p.Val274Thr -3.154598
386  p.Val274Tyr -2.009175

[387 rows x 2 columns]

In [12]:
aggregated.to_csv(dataset_path / "scoreset.csv", index=False)