In [2]:
import pandas as pd
from pathlib import Path
import json
dataset_path = Path("/mnt/i/bio/mave_curation/vanLoggerenberg_HMBS_ubiquitous/")
assert dataset_path.exists()

In [5]:
data = pd.read_csv(dataset_path / "raw" / "urn_mavedb_00000108-a-1_scores.csv")

In [6]:
data

,accession,hgvs_nt,hgvs_splice,hgvs_pro,score,sd,df,se
0,urn:mavedb:00000108-a-1#1,NaN,NaN,p.Val94Tyr,0.078732,0.240569,2,0.170108
1,urn:mavedb:00000108-a-1#2,NaN,NaN,p.Val94Trp,-0.641036,0.184045,2,0.130139
2,urn:mavedb:00000108-a-1#3,NaN,NaN,p.Val94Thr,0.456650,0.345503,4,0.172751
3,urn:mavedb:00000108-a-1#4,NaN,NaN,p.Val94Ter,0.548358,0.207878,2,0.146992
4,urn:mavedb:00000108-a-1#5,NaN,NaN,p.Val94Ser,-0.193890,0.461795,6,0.188527
...,...,...,...,...,...,...,...,...
6039,urn:mavedb:00000108-a-1#6040,NaN,NaN,p.Ala112Cys,1.102460,0.129974,2,0.091905
6040,urn:mavedb:00000108-a-1#6041,NaN,NaN,p.Ala112Asp,-0.035792,0.390035,4,0.195018
6041,urn:mavedb:00000108-a-1#6042,NaN,NaN,p.Ala112Asn,-0.631452,0.714959,2,0.505553
6042,urn:mavedb:00000108-a-1#6043,NaN,NaN,p.Ala112Arg,-0.533869,0.488109,4,0.244055
6043,urn:mavedb:00000108-a-1#6044,NaN,NaN,p.Ala112=,1.002454,0.081308,4,0.040654

In [7]:
data = data[(~data.hgvs_pro.isna()) & (~data.score.isna())]

In [9]:
data.to_csv(dataset_path / "scoreset.csv", index=False)

In [3]:
metadata = dict(uniprot_acc='P08397')
with open(dataset_path / 'metadata.json', 'w') as f:
    json.dump(metadata, f)