In [2]:
import pandas as pd
from pathlib import Path
import json
dataset_path = Path("/data/dzeiberg/mave_calibration/data/vanLoggerenberg_HMBS_erythroid/")
assert dataset_path.exists()
AUTHOR_TRANSCRIPT = "NM_000190.4"

In [3]:
data = pd.read_csv(dataset_path / "raw" / "urn_mavedb_00000108-a-2_scores.csv")
data = data.assign(author_transcript=AUTHOR_TRANSCRIPT)

In [4]:
data

,accession,hgvs_nt,hgvs_splice,hgvs_pro,score,sd,df,se,author_transcript
0,urn:mavedb:00000108-a-2#1,NaN,NaN,p.Val94Tyr,0.011268,0.400078,2,0.282898,NM_000190.4
1,urn:mavedb:00000108-a-2#2,NaN,NaN,p.Val94Trp,-0.601767,0.199376,2,0.140980,NM_000190.4
2,urn:mavedb:00000108-a-2#3,NaN,NaN,p.Val94Thr,0.488784,0.473580,4,0.236790,NM_000190.4
3,urn:mavedb:00000108-a-2#4,NaN,NaN,p.Val94Ter,0.438297,0.256071,2,0.181069,NM_000190.4
4,urn:mavedb:00000108-a-2#5,NaN,NaN,p.Val94Ser,-0.243077,0.367972,6,0.150224,NM_000190.4
...,...,...,...,...,...,...,...,...,...
6481,urn:mavedb:00000108-a-2#6482,NaN,NaN,p.Ala112Cys,1.113248,0.151411,2,0.107064,NM_000190.4
6482,urn:mavedb:00000108-a-2#6483,NaN,NaN,p.Ala112Asp,0.163642,0.201522,4,0.100761,NM_000190.4
6483,urn:mavedb:00000108-a-2#6484,NaN,NaN,p.Ala112Asn,-0.701918,0.757431,2,0.535584,NM_000190.4
6484,urn:mavedb:00000108-a-2#6485,NaN,NaN,p.Ala112Arg,-0.534498,0.605914,4,0.302957,NM_000190.4
6485,urn:mavedb:00000108-a-2#6486,NaN,NaN,p.Ala112=,1.029030,0.085064,4,0.042532,NM_000190.4

In [5]:
data = data[(~data.hgvs_pro.isna()) & (~data.score.isna())]

In [6]:
data.to_csv(dataset_path / "scoreset.csv", index=False)

In [8]:
metadata = dict(uniprot_acc='P08397')
with open(dataset_path / 'metadata.json', 'w') as f:
    json.dump(metadata, f)